version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data/

    healthcheck:
      test: "nc -z localhost 5432"
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile

#    command: npm start

    ports:
      - '3000:3000'

    volumes:
      - ./react/react_project:/app/frontend
      - /app/frontend/node_modules
#      -         ./react/react_project/node_modules:

    depends_on:
      - backend

  backend:
    build:
      context: ./django
      dockerfile: Dockerfile

    command: >
        sh -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    ports:
      - '8000:8000'

    volumes:
      - ./django/django_project:/app/backend

    depends_on:
        db:
          condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"