version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./react/react_project:/app/frontend
      - ./react/react_project/node_modules:/app/frontend/node_modules

    depends_on:
      - backend

  backend:
    build:
      context: ./django
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    ports:
      - '8000:8000'

    volumes:
      - ./django/django_project:/app/backend

    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"